name: Unpack tgz Files

on:
  push:
    paths:
      - '*.tgz'
  pull_request:
    paths:
      - '*.tgz'
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  unpack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create /src directory if it doesn't exist
        run: mkdir -p src

      - name: List tgz files
        run: |
          echo "Listing tgz files in root directory:"
          ls *.tgz || echo "No tgz files found"

      - name: Extract tgz files
        run: |
          for tgzfile in *.tgz; do
            if [ -f "$tgzfile" ]; then
              dirname=$(basename "$tgzfile" .tgz)
              mkdir -p "src/$dirname"
              tgz -xf "$tgzfile" -C "src/$dirname"
              echo "Unpacked $tgzfile into src/$dirname"
            fi
          done
